### ISSUE TITLE
Small UI Glitch 

### ISSUE THREAD

**Issue by SeanTheFolder** [pmotschmann/Evolve#1053]
[evolve-2024-01-31-21-19.txt](https://github.com/pmotschmann/Evolve/files/14120726/evolve-2024-01-31-21-19.txt)

When greater than 3 WardenClyffe are queued, the color of the $ requirement and Sheet Metal are gradients rather than solid colors. This may be intentional when I think about it, but it seems odd to me so I thought I would post it in case it is not intentional. Maybe instead of that do a can craft up to number in parentheses next to the material required that is color coded, white for possible, red for not, etc, for example:

[Building/Name] | Cap Too Low
-------------------------------
Resource 1         | (1) (2) (3) (4) (5)
Resource 2         | (1) (2) (3) (4) (5)
Resource 3         | (1) (2) (3) (4) (5)
...
-------------------------------
Details
...

P.S.
Phenomenal game, thank you so much for making it open source, and a free to play with donations monetization model. I will certainly be sending you a cup of coffee or pint on me every so often. You deserve it. Keep up the great work!

**Comment by SeanTheFolder** [comment]
For some reason reloading the save from the file fixed the second issue. So, I removed it and updated the Issue.

**Comment by zyx-xyzzy** [comment]
Not a bug, gradients are used to show that the resource that's currently bottlenecking production of the first copy of the building in queue is different from the one for producing the whole stack. (Also, if I can be nitpicky for a sec, it's "Wardenclyffe" not "WardenClyffe", and your diagram of your proposed alternative UI barely makes any sense since whatever method you used to try and add color to it didn't work.)

**Comment by SeanTheFolder** [comment]
Thanks.
