### ISSUE TITLE
Bug: Wiki Fanaticism and Anthropology doubled

### ISSUE THREAD

**Issue by toman222** [pmotschmann/Evolve#354]
![image](https://user-images.githubusercontent.com/14962962/81695087-6fb41480-9462-11ea-8145-dfed86855224.png)

**Comment by boozledorf** [comment]
This is caused by the fact that the code base has Fanaticism and Anthropology listed twice.  See:
https://github.com/pmotschmann/Evolve/blob/master/src/actions.js#L10634
https://github.com/pmotschmann/Evolve/blob/master/src/actions.js#L10659

The first one locks once you get the Transcendence upgrade, while the second locks _until_ you have it (meaning only one of them will ever be visible at a time).  The first one will also lock Anthropology as well, but the second does not.
