### ISSUE TITLE
Stress Breakdown

### ISSUE THREAD

**Issue by pmotschmann** [pmotschmann/Evolve#40]
Players are finding the stress system to be unintuitive or unclear, this needs some informational improvements to help players understand the system easier and how to manage it.

**Comment by CapnCrinklepants** [comment]
Maybe stress could be eliminated and replaced with a few different categories like "Unemployment" and "Crowding". The would-be Crowding category seems to be calculated in a rather complicated manner: Every 5 units in any particular job raises Stress by 1, which I think seems to imply that it's better to spread all available workers as evenly as possible across all jobs, which isn't possible with food management etc. I think the intended mechanic was to have a general increase in stress for every 5 citizens in general. In which case, and due to using .toFixed(0) in the forEach(job) (line 582, main.js) causes some strange tier-like effects per job. Fixing that might imbalance the stress_level and entertainment mechanics. Then again, entertainment might be able to overtake stress and make chasing the >100% morale bonus feel better.

I'll leave the creative decisions to you, but I don't mind implementing after, so long as my motivation continues :)

**Comment by pmotschmann** [comment]
I wrote it on a per job level because it seemed like a more interesting way to implement the mechanic. I personally feel like the balance on it is pretty decent right now but I might be biased. It's pretty easy to cap morale later when you have TV unlocked and a ton of wardenclyffe towers, this certainly doesn't help early game though.

You are right in that you could get lower stress by spreading your labor around evenly but I didn't consider this to be a big deal as you won't be able to get a lot out of engineering it and it costs you the opportunity of increasing production where it's most needed.

I don't feel like the current implementation is the best it can be overall, but I need to give some more thought to it. At the very least breaking unemployment out into it's own morale line item is warranted. I may need to change the label from stress to something else as it's overly vague.

**Comment by pmotschmann** [comment]
I'm thinking of rescaling all this as part of a bigger overhaul which will make rank 1 entertainers more impactful.
