### ISSUE TITLE
Incorrect time to completion for items in build queue

### ISSUE THREAD

**Issue by AaronSofaer** [pmotschmann/Evolve#414]
As you can see in the attached image, there is an incorrect time to completion for items in the build queue. A Supercollider consumes no He3; the Dis Mission will be eligible to be built before the Supercollider is finished, and will therefore fire as soon as the project is done. It will not take an additional 15 minutes.

![image](https://user-images.githubusercontent.com/2935149/89572860-945c2600-d7de-11ea-99e7-2b66fb68b2f4.png)

**Comment by boozledorf** [comment]
I've noticed a general inconsistency with queue times when there is an ARPA project in the queue.  It tends to inflate or deflate the time of everything else (sometimes even itself) with no rhyme or reason.

**Comment by Zackh1998** [comment]
I'm 99% sure I see the problem here. The problem is related to the fact that the build queue keeps a resource tracker to keep track of about how many resources you should have in the future after each build queue item is complete. The problem is that the build queue resource tracker is only adding in the time it takes to complete a single Arpa segment (even though the full complete time is shown in the queue).

Therefore, when it calculates the cost for the 'Dis Mission', it only thinks that the time to construct the next Arpa segment has passed (25 seconds in this case). The game knows that it's going to take 16m 55s to generate enough Helium 3, but its calcuating that you'll only have 25 seconds of production by the time you finish the Supercollider, which means it thinks you'd need another 16m 30s to complete the 'Dis Mission' after it finished. (18m 14s + 16m 55s - 25s = 34m 44s)

I have a fix for it locally. I'm going to test it tomorrow and submit a PR to fix this.

**Comment by Zackh1998** [comment]
This PR fixes this arpa queue time issue.
