### ISSUE TITLE
Bug(s) universe-specific mastery bonus from challenge perks

### ISSUE THREAD

**Issue by jaahay** [pmotschmann/Evolve#435]
Specific is missing an `i`.
"%0% of Standard Mastery and %1% of Universe-specific Mastery works in alternate universes"
https://github.com/pmotschmann/Evolve/blob/7a24e5acee8eff7ff60fcd01a997719ef04f6191/strings/strings.json#L2320

-- 
I detect an inconsistency with what universe-specific mastery is displayed as (arpa_genepool_universal_desc), versus what it is actually calculated.
Challenge CRISPR Level | Displayed Bonus | Actual Bonus
-------------------------- | ------------------ | --------------
1 | 60% | 40%
2 | 60% | 40%
3 | 60% | 60%
4 | 40% | 40%
5 | 40% | 40%

Displayed:
https://github.com/pmotschmann/Evolve/blob/7a24e5acee8eff7ff60fcd01a997719ef04f6191/src/achieve.js#L936

Calculated:
https://github.com/pmotschmann/Evolve/blob/8cd4ff05d7863e9925cd30f8d9f968a6e178e97c/src/functions.js#L829-L851

--
Suggestion: change `arpa_genepool_universal_desc` to indicate you start with 40% which is then raised to 60% i.e., `Universe specific mastery is increased from 40% to 60%`

--
Is universe-specific mastery bonus supposed to go down at challenge level 4?

**Comment by Beorseder** [comment]
The 
"perks.append(`<div><span class="has-text-warning">${loc("arpa_perks_challenge2",[global.genes['challenge'] >= 4 ? 80 : 60, global.genes['challenge'] >= 4 ? 40 : 60])}</span></div>`);"
line displaying your Standard and Universal Mastery rates only appears in your perks list if you have the Universal CRISPR upgrade. Thus, at Challenge CRISPR Levels 1 and 2, there is no incorrect displaying of the Universal Mastery rate, as it is not displayed at all.
Universal Mastery is supposed to go down to 40% with Challenge4. Standard Mastery has the capacity to provide more than Universal Mastery, because each universe does not have all of the achievements in the game, so moving that 20% over to Standard Mastery from Universal Mastery is still a net increase. It's also more helpful for when you're going into a universe where you do not have many achievements completed, as your overall Mastery goes down by less.

**Comment by jaahay** [comment]
Sounds good, thanks for answering!
