### ISSUE TITLE
Bug: Undefined Pirate Threat

### ISSUE THREAD

**Issue by Revanchism** [pmotschmann/Evolve#597]
Unsure what, exactly, has caused this to happen but upon attempting an Ascension run following a Banana Republic finish I noticed that the pirates are listed as 'Undefined'. Instead of resetting I instead have pushed on and have run into the problem where said undefined pirates seem to cause the code to break spectacularly upon researching 'Cruiser Ship'. Refreshing doesn't fix this problem nor does saving/loading - indeed doing so only causes everything to break further.

Notes: The save was originally from a few months ago and was only picked back up recently. 
The attached save is a backup from before researching cruisers though this reported bug has now happened twice in a row at the same point.
[evolve-2021-6-9.txt](https://github.com/pmotschmann/Evolve/files/6626414/evolve-2021-6-9.txt)

**Comment by Beorseder** [comment]
This bug was caused by the custom species being selected as an alien before having done an Ascension run before to define it, and was fixed 23 days ago in: https://github.com/pmotschmann/Evolve/pull/586
So this is only an issue now because it the save is so old. Here's a fixed up version of the save that'll work:
[Fixed Save.txt](https://github.com/pmotschmann/Evolve/files/6627298/Fixed.Save.txt)

**Comment by Revanchism** [comment]
Cheers, that fixed it right up!
