### ISSUE TITLE
Where is the Prestige Icon?

### ISSUE THREAD

**Issue by TTSKarlsson** [pmotschmann/Evolve#608]
I've played this game on and off for years but never found any icon matching the name you choose in the settings. Is it just in settings for fun, or is there supposed to be an icon somewhere? I couldn't find anything about that setting in the wiki.

![image](https://user-images.githubusercontent.com/9962943/123544341-205aa180-d753-11eb-9a2d-3519df4eadca.png)

If there's supposed to be an icon somewhere in the game, maybe there could be a tooltip on the setting to hint at where you can dig down and find it?

**Comment by Beorseder** [comment]
It shows in a bunch of places, like near the planet name, where it denotes how many Challenge Genes you have active.
![image](https://user-images.githubusercontent.com/45007766/123544734-df8e6880-d711-11eb-8249-d95d0a5a7058.png)
Also shows as the general icon for achievements that you've earned on 1star or higher.
![image](https://user-images.githubusercontent.com/45007766/123544771-09e02600-d712-11eb-8b9c-8edde9707169.png)
And on Feats that don't award their own icons.
![image](https://user-images.githubusercontent.com/45007766/123544799-2714f480-d712-11eb-8af9-737bc593b25f.png)
And on Sentience to denote whether you have earned the general level of the greatness achievement for the genus and at what #star, and on individual species themselves to denote the same with the destruction achievement for that species.
![image](https://user-images.githubusercontent.com/45007766/123544832-68a59f80-d712-11eb-89bf-3729e66b0e93.png)

By default it's the Star, but various Feats award other icons you can use to replace it, which will make it show that icon instead of the Star in all of those places.
Star:
![image](https://user-images.githubusercontent.com/45007766/123544876-a4d90000-d712-11eb-8d18-c329061b402d.png)
Taijitu:
![image](https://user-images.githubusercontent.com/45007766/123544862-968ae400-d712-11eb-97e1-b5d716348d09.png)

**Comment by TTSKarlsson** [comment]
It has never shown for me, at any of those places:

![image](https://user-images.githubusercontent.com/9962943/123545037-6fee9c80-d756-11eb-9bc1-d62ae5e9fb1b.png)

![image](https://user-images.githubusercontent.com/9962943/123545099-a3312b80-d756-11eb-994e-4b1bba3cf3a6.png)

And those feat menus doesn't even exist on 
https://pmotschmann.github.io/Evolve/

**Comment by Beorseder** [comment]
Well then you've just never done a run higher than 0star. Try turning on some Challenge Genes, they're pretty vital to getting Mastery higher, which is crucial for speeding up gameplay.
https://pmotschmann.github.io/Evolve/wiki.html#mechanics-gameplay-challenge
https://pmotschmann.github.io/Evolve/wiki.html#mechanics-gameplay-mastery
https://pmotschmann.github.io/Evolve/wiki.html#feats-achievements

**Comment by TTSKarlsson** [comment]
Ah, I understood from the wiki that feats was only for completionists, so I never activated any challenge gene, but killing the demon lord doesn't take very long with a few thousand plasmids, phage and all the crispr and most bloodstones unlocked either.

**Comment by Beorseder** [comment]
Yeah Feats have no mechanical benefit, but that's not really related to the topic at hand. Achievements provide Mastery, a global production bonus. They provide more Mastery when earned with higher Challenge Genes active. Mastery, among other bonuses, lets me do an Ascension run in 1.5 hours.

**Comment by TTSKarlsson** [comment]
I have plenty Mastery though, it doesn't really provide much of a bonus, but that's not really the point either, I guess. With much plasmids and phage you do a demonic infusion or two in a work day. But I guess I will do a challengegene thing just to enable the icon.

**Comment by TTSKarlsson** [comment]
A tooltip that tells that you need to do a challenge gene run to unlock it would be nice in the settings then.

Thanks for telling me how it works!

**Comment by Beorseder** [comment]
Well it's not doing much because you don't have a lot of it. You have only 43 achievements, and I presume they're all earned on 0star, so in Standard you're only getting a +10.75% production bonus from them.
With all achievements earned and all at 4star, my Mastery is giving me over a +200% production bonus.
Also, most achievement-based perks scale in effect based the level you have earned of the achievement. So it's not just Mastery, but other perks as well.
https://pmotschmann.github.io/Evolve/wiki.html#perks-prestige

**Comment by TTSKarlsson** [comment]
I wonder if having all challenge genes on with 1.45x prestige really is worth it though, it will take a lot longer than normal to reach ascension. Probably more than 45% longer.

I also don't really play games much for achievements either, so they're just side bonuses or fun facts. I'm also playing on my private server and not on github, but had a really old save on here on github that was worth using as example to show that I don't get to see the icon on "the official version" so to speak.

I really appreciate the effort you put in to help, thanks again!

**Comment by TTSKarlsson** [comment]
I'm closing this as the question is answered in this thread.
