### ISSUE TITLE
Gun Emplacements dipped into negative requirement

### ISSUE THREAD

**Issue by N-Plus-Plus** [pmotschmann/Evolve#676]
[gunemplacement.txt](https://github.com/pmotschmann/Evolve/files/7777617/gunemplacement.txt)
Save file attached.

**Comment by Beorseder** [comment]
If you're talking about this line
![image](https://user-images.githubusercontent.com/45007766/154181077-3bb4366a-fd15-4e19-aa2a-3bdae3cfb669.png)
That's not a requirement of the Gun Emplacement. That's an effect of the Gun Emplacement that for each one you have on you require 2 fewer Soldiers manning the Soul Forge. `Soul Forge: -2 Soldiers Required` = `This Gun Emplacement's doing some hard work killing demons around The Pit, so much work that you can take 2 Soldiers off of guarding the Soul Forge because they're just wasting their time there.`

**Comment by N-Plus-Plus** [comment]
Well, it seems so obvious in hindsight ... Many thanks for the clarification - closing the issue now with bright red cheeks :)
