### ISSUE TITLE
Bug:The alloy's and polymer‘s names  are conversely

### ISSUE THREAD

**Issue by universeexplor** [pmotschmann/Evolve#746]

**Comment by tomwollert** [comment]
I think this is the same problem I'm having (hard to tell from the description by the OP :D). Today I noticed that a bunch of resources are just labelled wrong. 

The descriptions that have their names switched (probably non exhaustive) are:
- Stone, Lumber
- Titanium, Steel
- Oil, Coal
![image](https://user-images.githubusercontent.com/38211243/161260038-3fbf0afb-ae0f-4128-913d-82fbffc07f27.png)
This includes tooltips (highlighting my lumber jacks say they produce stone, and research states it needs oil, which I'm not producing instead of coal)
